### PR TITLE
Create nimble_distance component

### PR DESCRIPTION
**Pull request by mvgijssel**
ref #115 

The `nimble_distance` component will implement the same logic for distance calculation as ESPresence does https://github.com/ESPresense/ESPresense/blob/master/lib/BleFingerprint/BleFingerprint.cpp#L489-L496. Currently ESPhome supports filters on sensor components, but this is not advanced enough just yet to really replicate the behaviour from ESPresence which is very accurate. Maybe in the future this can be implemented in a more general way instead of needing a separate component.

The idea behind the design is that the `NimbleDeviceListener` will figure out if there is a match with a passed in `advertised_device`. If there is a match then a virtual method `update_state` will be called which needs to be implemented by the `nimble_rssi` and `nimble_distance` components.

## TODO

- [x] Test using a Shelly connected to Home Assistant and see if OTA still works
- [x] Test if we can configure MQTT client on the Shelly and make the ble_distance sensor not report to Home Assistant (`internal: true`)
- [x] Send MQTT messages whenever the `ble_distance` sensor triggers sending a message for the `mqtt_room` component
- [x] Does this work for longer periods of time? Seems to report `not_home` after running for ~20 minutes. Does NimBLE stop scanning? Could be due to the limit on known devices! Can we somehow prune this list?
  - Happens because the known_devices list if full and the new random mac cannot be added. Need to change the NimBLEScan to have no limit and create a copy of the NimBLEAdvertisedDevice in the callback as the original is deleted immediately after the callback.
- [x] Figure out how to use the external component in the home installed shellys (at home-assistant/esphome-data/*)
- [x] Make sure ESP_LOGD maps to NIMBLE_LOGD (fixed in https://github.com/h2zero/esp-nimble-cpp/pull/42/files)
- [x] Determine the update rate, how often should the sensor send an event to Home Assistant? Currently use the same as ESPresence 100ms scan window with a 100ms scan interval.
- [ ] Setup ota mode after clicking button sequence (5x click?) in case of emergency and WiFi connection no longer working 
- [ ] Move all of the variables used in distance calculation into ESPHome configuration with sane default values 
- [ ] Ability to specify a default "Measured Power" or "Tx Power" for the `ble_distance` component (so it's not inferred from the advertised device)

### CODE REVIEW

**Comment by mvgijssel** [comment]
Let the nimble_tracker with nimble_distance for an Apple Watch for over an hour without any problem 🎉.

**Comment by jsnyde30** [comment]
I've been following along with this project for a few days now and would love to help with testing, but I keep getting an error when trying to install this on my esp-wroom-32 chips.  This is an epic project and could really help out with bridging the gap between espresense and esphome.  great work @mvgijssel !!

Tool Manager: Installing platformio/toolchain-esp32ulp @ ~1.22851.0
INFO Installing platformio/toolchain-esp32ulp @ ~1.22851.0
Error: Could not find the package with 'platformio/toolchain-esp32ulp @ ~1.22851.0' requirements for your system 'linux_aarch64'

I've tried quite a few things but not really finding any help on the web.  wanted to reach out and see if you noticed this during your testing.

**Comment by jsnyde30** [comment]
@mvgijssel thanks man!  I've been pulling my hair out for 2 days now lol.  I'll try the old trust macbook out.

**Comment by jsnyde30** [comment]
@mvgijssel I had to set up a 2nd esphome instance on my NAS, but I was able to install, set up a sensor for my android phone with IRK and it's working!!  I have an old iphone I can test with for multi-device tracking, then there's only 2 things left to figure out; multiple sensors in different rooms, and how to make regular ibeacons work.

Great job on this project!  It would be epic if I could replace all 9 of my espresense devices with ESPHomes because sensors seem to be way more reliable with the later.

If you need help or testing for this project, feel free to reach out.

**Comment by mvgijssel** [comment]
Sorry for the late reply 🤦‍♂️. 

> @mvgijssel I had to set up a 2nd esphome instance on my NAS, but I was able to install, set up a sensor for my android phone with IRK and it's working!! 

Great to hear! 💪 

> multiple sensors in different rooms

I'm about to add a second Apple Watch to the setup, so will let you know how that works!

> and how to make regular ibeacons work.

I _think_ adding iBeacon (or any other device for that matter) support _should_ not be too hard, though note I'm a big c++ n00b 🙈. 

I've built the `nimble_tracker` component to validate if it's feasible to do room occupancy using Apple Watch bluetooth object tracking. If I get positive results then I'll contact the ESPHome peeps to see what it takes to upstream the NimBLE based BLE library in place of/next to the existing Bluedroid, so everyone can use it to track all BLE devices! 

BTW if you are investigating room occupancy using BLE devices as well, after finding [mqtt_room](https://www.home-assistant.io/integrations/mqtt_room/) and [ad-espresense-ips](https://github.com/ESPresense/ad-espresense-ips) too noisy, I'm now trying [find3](https://github.com/schollz/find3) in https://github.com/mvgijssel/setup/issues/153 with some good results so far!

**Pull request merged**
